[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-sql-driver/mysql"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-sqlite3"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/cli"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  branch = "master"
  name = "github.com/suzuken/yamlssm"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  branch = "master"
  name = "gopkg.in/gorp.v1"
